### ISSUE TITLE
Backend - implement ConnectionController/AdminController

### ISSUE THREAD

**Issue by TheseusDeus** [capgemini-stavanger/gi-en-jul#118]
Start with a basic controller for the admin page
Should do something easy like displaying families

Admin should be able to:
- [ ] Get list of unmatched families and unmatched givers
- [ ] Match family with giver
- [ ] Get matched families with their giver

**Comment by Sommerli** [comment]
Do #163 before this

**Comment by Sommerli** [comment]
Split into multiple issues
#220 
#221
