### ISSUE TITLE
(Give feedback) Backend - Add some properties to help filtering Recipients and Givers 

### ISSUE THREAD

**Issue by Sommerli** [capgemini-stavanger/gi-en-jul#163]
To simplify queries, and utilizing Table Storage for all its worth, we should add some helper-properties to some tables.

Both Recipients and Givers should contain a property if they have completed a match or not. 
My suggestion is below

Add two properties to Givers and Recipients, IsSuggestedMatch and HasConfirmedMatch.
These could be boolean or the GiverId/RecipientId which is suggested.

**Comment by TheseusDeus** [comment]
A boolean for each of them works fine, and the naming with "is" and "has" is good for readability

**Comment by elisabethnetland** [comment]
Is it necessary to add a property of completed as well! For when the giver confirms that they will buy via the email link?

**Comment by Sommerli** [comment]
> Is it necessary to add a property of completed as well! For when the giver confirms that they will buy via the email link?

When givers are assigned to a receiver, both the receiver and giver needs to be "on hold", otherwise it will be possible to double-assign a receiver

Which is why i belive at least two values should be assigned
