### ISSUE TITLE
Frontend - Method for mobile view of textInput

### ISSUE THREAD

**Issue by elisabethnetland** [capgemini-stavanger/gi-en-jul#177]
![image](https://user-images.githubusercontent.com/37541100/124587018-73211100-de57-11eb-8614-5622c9658156.png)

Possible solutions: 
PlaceholderText is removed if the placeholderText exceeds the input field.
Truncate the placeholders, and/or set overflow to none.

**Comment by TheseusDeus** [comment]
Did this get fixed with the new isMobile() function in #167 @elisabethnetland ?

**Comment by TheseusDeus** [comment]
Was this fixed with one of your older PRs @joffe97

**Comment by TheseusDeus** [comment]
not applicable since the recipient page is for web view
