### ISSUE TITLE
Frontend - Change all occurrences of any into a suitable type.

### ISSUE THREAD

**Issue by joffe97** [capgemini-stavanger/gi-en-jul#193]
There shouldn't be any usage of the `any` type. Change to a suitable type, or `unknown` if the type really is unknown.

**Comment by TheseusDeus** [comment]
This issue should be way more specific. Like the actual files or just close the issue

**Comment by Sommerli** [comment]
Closing as the issue is unspecific and somewhat solved with refactoring that has been done
