### ISSUE TITLE
Frontend -Make api hook

### ISSUE THREAD

**Issue by TheseusDeus** [capgemini-stavanger/gi-en-jul#198]
Make custom hook for API GET and POST with our backend
Without authorization

**Comment by TheseusDeus** [comment]
Next step would be to implement a way for it to authorize with the Auth0 managment API,
then use that token when POSTing to the backend. 
This would be too big for this issue and therefore i will start with this base. Sounds good @Sommerli ?

**Comment by Sommerli** [comment]
link from Antonio: https://javascript.plainenglish.io/custom-hook-in-react-js-for-calling-api-useapi-7de24b42729c
And example from other project 
`import { useEffect, useState } from 'react';
const useFetch = <T extends any>(url: string, options: RequestInit) => {
  const [response, setResponse] = useState<T>();
  const [error, setError] = useState(null);
  useEffect(() => {
    const fetchData = async () => {
      try {
        const res = await fetch(`${process.env.REACT_APP_API_BASE_URL}/${url}`, options);
        if (!res.ok) {
          throw new Error(`${res.status} ${res.statusText}`);
        }
        const json = await res.json();
        setResponse(json);
      } catch (error) {
        setError(error);
      }
    };
    fetchData();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
  return { response, error };
};
export default useFetch;`

**Comment by TheseusDeus** [comment]
Could not succeed in implementing it

**Comment by TheseusDeus** [comment]
closed with #204 and #207
