### ISSUE TITLE
Actions - Frontend files are not being updated on deployment to Azure

### ISSUE THREAD

**Issue by Sommerli** [capgemini-stavanger/gi-en-jul#201]
Any changes to frontend are not included when deploying to Azure it seems.

Example: registrer familie has not yet updated to MaterialUI #113 
![image](https://user-images.githubusercontent.com/45152025/125268019-9809fe00-e307-11eb-8680-1b6484cfa8f4.png)

**Comment by TheseusDeus** [comment]
![registrer](https://user-images.githubusercontent.com/46569868/125272366-0c46a080-e30c-11eb-8143-2541862dd87b.PNG)
It does work, but it is inconsistent at best. This will probs be fixed with #191

**Comment by Sommerli** [comment]
Fixed by clearing site data of the website.

![image](https://user-images.githubusercontent.com/45152025/125432723-2c949644-df17-42a4-94ae-300d778abe2f.png)
