### ISSUE TITLE
Backend - Routing when having an input

### ISSUE THREAD

**Issue by elisabethnetland** [capgemini-stavanger/gi-en-jul#214]
![image](https://user-images.githubusercontent.com/37541100/125448595-469cdd38-fc0e-4085-942a-6ea76e72da8d.png)

Find out best practice of routing when having an input to the controller. 
 
https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-5.0&tabs=visual-studio#routing-and-url-paths

**Comment by Sommerli** [comment]
Any update here?

**Comment by TheseusDeus** [comment]
closed
