### ISSUE TITLE
Frontend - Delete recipient in admin overview page

### ISSUE THREAD

**Issue by elisabethnetland** [capgemini-stavanger/gi-en-jul#216]
**Is your feature request related to a problem? Please describe.**
There is no way for the admin to delete a recipient from the webpage.

**Describe the solution you'd like**
Possibility for the admin to delete recipients that are not correct in overview page. 

**Describe alternatives you've considered**
My idea is to have a delete button for each accordion in the recipient table in the overview page: 
![image](https://user-images.githubusercontent.com/37541100/125449442-05a9532d-79e3-4923-aafb-5d9c3a9a501f.png)
Like the save button here. Picture taken from: https://material-ui.com/components/accordion/

**Additional context**
The backend for this is already implemented in issue #219:
- Path: /api/admin/recipient
- Method: DELETE
- Body: DeleteRecipienDto (rowkey and primary key)
Issue #219 doesn't delete family members. Issue #376 should be solved before the recipients is deleted, so data without references is not stored in the database.

**Comment by TTorgersen** [comment]
This issue won't fix because of "Delete person" function will not work. Related to [fix367](https://github.com/capgemini-stavanger/gi-en-jul/issues/367)
