### ISSUE TITLE
Backend - fetch givers sorted

### ISSUE THREAD

**Issue by elisabethnetland** [capgemini-stavanger/gi-en-jul#220]
Create functions in admin controller that returns a list of givers sorted in these orders: 
- [ ] asc on Fullname
- [ ] desc on Fullname
- [ ] asc on Familysize
- [ ] desc on Familysize
- [ ] asc on hasConfirmedMatch
- [ ] desc on hasConfirmedMatch

My idea is that we have three columns above the giverTable with the fields Fullt navn, Familiesammensetning and Koblet, each with an toggle arrow. When you toggle you fetch the correct sorting from the backend. 
Example in picture with Navn and Idag%. 
![image](https://user-images.githubusercontent.com/37541100/125580348-fa261098-c946-4ec5-99e4-c9ab32f43845.png)

 EDIT: 
This could also be done in the frontend by sorting the giverData

**Comment by Sommerli** [comment]
📈

**Comment by Sommerli** [comment]
This will be done in frontend.
