### ISSUE TITLE
Backend - fetch sorted recipients

### ISSUE THREAD

**Issue by elisabethnetland** [capgemini-stavanger/gi-en-jul#221]
Create functions in admin controller that returns a list of recipients sorted in these orders: 
- [ ] asc on referenceId
- [ ] desc on referenceId
- [ ] asc on Familysize
- [ ] desc on Familysize
- [ ] asc on hasConfirmedMatch
- [ ] desc on hasConfirmedMatch

My idea is that we have three columns above the recipientTable with the fields FamilieID, Familiesammensetning and Koblet?, each with an toggle arrow. When you toggle you fetch the correct sorting from the backend. 
Example in picture with Navn and Idag%. 
![image](https://user-images.githubusercontent.com/37541100/125580348-fa261098-c946-4ec5-99e4-c9ab32f43845.png)

EDIT:
This could also be done in the frontend by sorting the giverData

**Comment by Sommerli** [comment]
This will be done frontend
