### ISSUE TITLE
Frontend - Sort giver table in admin overview page in asc and desc

### ISSUE THREAD

**Issue by elisabethnetland** [capgemini-stavanger/gi-en-jul#222]
**Is your feature request related to a problem? Please describe.**
The giver table in the admin overview page could be easier to use.

**Describe the solution you'd like**
There should be a sorting functionality that sorts on e.g. `Fullt navn`, `Familiesammensetning` and `Koblet`. This should be able to sort both ascending and descending.

**Describe alternatives you've considered**
A toggle arrow could be used for each of the sorting options, that toggles ascending and descending sorting.

**Additional context**
![image](https://user-images.githubusercontent.com/37541100/125580993-85fd8d5d-fd6f-4375-acfd-71fc1a74e906.png)
The solution here should be similar to the solution in issue #223.

**Comment by Sommerli** [comment]
GiverTable should be recreated as a DataGrid
https://material-ui.com/components/data-grid/

**Comment by Sommerli** [comment]
Not relevant for our project owner
