### ISSUE TITLE
Backend - Error 500 when submitting giver form

### ISSUE THREAD

**Issue by joffe97** [capgemini-stavanger/gi-en-jul#254]
The giver is registered, but error 500 occur. This may happen because of the mailing system.

**Comment by joffe97** [comment]
This happens because the email used is not valid. Will be fixed when configuring email with github actions.

**Comment by Sommerli** [comment]
When testing locally, use papercut to solve this. https://github.com/ChangemakerStudios/Papercut-SMTP/releases
Download the .exe file.

**Comment by TheseusDeus** [comment]
does that solve the problem @Sommerli?

**Comment by Sommerli** [comment]
Yep
