### ISSUE TITLE
Email or Frontend - Givers must receive a shopping list upon accepting a connection

### ISSUE THREAD

**Issue by Sommerli** [capgemini-stavanger/gi-en-jul#274]
Givers should get:
- a shopping list 
- family-referenceid 
- delivery location 
 
after they accept a connection.

This could be done via email or via frontend. 
Email is probably best option, as the giver is less likely to lose the information then.

**Comment by TheseusDeus** [comment]
Will agree with you upon this. Would be best to send a mail
