### ISSUE TITLE
Improve performance on Admin Connection 

### ISSUE THREAD

**Issue by elisabethnetland** [capgemini-stavanger/gi-en-jul#281]
See suggestion in issue #262 
Other suggestions: 
- Add the following setting to accordions
![image](https://user-images.githubusercontent.com/37541100/126754713-699af4a3-0bda-442a-924b-e25078789af7.png)
- Only fetch accordion summary and fetch details when expanding

**Comment by Sommerli** [comment]
What i see is that the tables should be rendered partly. Some rows at a time.

**Comment by TheseusDeus** [comment]
Agreed @Sommerli. Would be best to just render some of of them, and introduce more with a scroll or button
