### ISSUE TITLE
Backend - Delete persons in family from the database in the `/api/admin/recipients, DELETE` route

### ISSUE THREAD

**Issue by joffe97** [capgemini-stavanger/gi-en-jul#367]
**Is your feature request related to a problem? Please describe.**
When a recipient is deleted, the persons in that family is not deleted from the database.

**Describe the solution you'd like**
When the `/api/admin/recipients` path is called with the `DELETE` method, all persons in that family should be deleted. 

**Describe alternatives you've considered**
This issue can be solved by modifying the `DeleteRecipientAsync` method in `AdminController.cs`. I suggest doing the following:
1. Call `_personRepository.GetAllByRecipientId(recipient_id)` after the recipient has been deleted.
2. Call `_personRepository.DeleteBatchAsync(persons)` with the family members fetched in the step above.

**Comment by TTorgersen** [comment]
There is an issue where Person objects will not be deleted from the CloudTable because the resource is not found.
