### ISSUE TITLE
Login loop

### ISSUE THREAD

**Issue by TheseusDeus** [capgemini-stavanger/gi-en-jul#372]
**Describe the bug**
Infinite loading loop after pressing *continue* on the login page

**To Reproduce**
1. Go to another browser than Chrome, or incognito mode
2. Open the website locally or on azure
3. Add */admin* to the url
4. Add login credentials
5. Press continue

**Expected behavior**
Redirect to uri/admin and display "Foreslåtte matcher"

**Desktop (please complete the following information):**
 - Browser [e.g. chrome incognito , safari, ++]

**Additional context**
Probably a redirect loop, so look at the settings for the application on manage.auth0.com
Function causing it: @auth0/auth0-react/src/with-authentication-required.tsx withAuthenticationRequired(), the useEffect loop in that module
Function is added to src/components/admin/Adminpage.tsx:72

**Comment by TTorgersen** [comment]
The login loop is related to this error, which occurs if you try to login to admin on localhost:
![image](https://user-images.githubusercontent.com/46501222/135257267-306b002a-e784-4a67-8beb-1ab1ed91647d.png)

**Comment by TTorgersen** [comment]
Workaround for users might be:
[User consent](https://auth0.com/docs/configure/applications/confidential-public-apps/user-consent-and-third-party-applications?_ga=2.123448076.668719166.1632903312-1536424066.1625582960&_gl=1*ig559y*rollup_ga*MTUzNjQyNDA2Ni4xNjI1NTgyOTYw*rollup_ga_F1G3E656YZ*MTYzMjkxMDY0NS41LjEuMTYzMjkxMzg2Mi40OA..#skip-consent-for-first-party-applications)

**Comment by TTorgersen** [comment]
This was fixed/worked around in auth0 by managing settings for API. 
If this setting is enabled, this API will skip user consent for applications flagged as First Party.
