### ISSUE TITLE
Backend - Fix typo in event table

### ISSUE THREAD

**Issue by joffe97** [capgemini-stavanger/gi-en-jul#374]
**Is your feature request related to a problem? Please describe.**
The deliveryAdress column name should be deliveryAddress instead. This is a typo.

**Describe the solution you'd like**
Change the table name of deliveryAddress in the azure portal.

**Additional context**
The table storage diagram has the correct naming of this column.

**Comment by TTorgersen** [comment]
The part-time students need access to the Azure portal before this issue can be fixed.
