### ISSUE TITLE
GDPR Delete Storage

### ISSUE THREAD

**Issue by TheseusDeus** [capgemini-stavanger/gi-en-jul#378]
In the "Personvernerklæring" it is stated that the data will be saved for 13 months to accomplish the project, but after this the data has to be deleted, or the application is violating the law.

### Solution
- [ ] Make endpoint to delete all givers and recipients for a event and remove the event

### Option
If this is done before the app is live, you could also make a function to generate statistics for the event. How many registered givers, how many persons got help, etc.
However then you would have to change the "personvernerklæring" as well, and state that after the 13 month period, anonymous would be generated from their personal data and kept for new projects

**Comment by joffe97** [comment]
This can be done in two ways:
#### - Manually:
Add an endpoint to the admin controller. The admin would then have to delete the data manually from the admin page.
#### - Automatically:
The associated admin data could be deleted automatically when the enddate of the event is reached. The data would not have to be stored for 13 months then, but only for the event duration.

Both of these methods could be implemented for more flexibility.

**Comment by RonHaland** [comment]
Deleted as a part of #601 when deleting old production env.
