### ISSUE TITLE
Config - Host app on "gienjul.no" domain

### ISSUE THREAD

**Issue by TTorgersen** [capgemini-stavanger/gi-en-jul#424]
**Is your feature request related to a problem? Please describe.**
We need to configure the live app to be hosted as gienjul.no. 

**Describe the solution you'd like**
We need to receive the information necessary from the domain administrator so that we can configure azure accordingly.

**Comment by Sommerli** [comment]
A new Azure resource group for hosting of the production environment has been created. This enviroment is configured to run on gienjul.no domain.
