### ISSUE TITLE
Smaller mobile screens introduce horizontal scrolling

### ISSUE THREAD

**Issue by HGodal** [capgemini-stavanger/gi-en-jul#446]
**Describe the bug**
When using some devices, the input fields are too wide, resulting in horizontal scrolling.

**To Reproduce**
1. Use i.e. iPhone 8 or SE.
2. Register as giver and navigate to the pages with input fields.

**Expected behavior**
The pages should not introduce horizontal scrolling.

**Comment by RonHaland** [comment]
fixed by new design changes
