### ISSUE TITLE
Givers dissapear from the "connections" page.

### ISSUE THREAD

**Issue by HGodal** [capgemini-stavanger/gi-en-jul#448]
**Describe the bug**
Sometimes when navigating the admin page, the givers under the tab "foreslåtte koblinger" dissapears.

**To Reproduce**
1. Log in as an admin
2. Navigate to "foreslåtte koblinger".

**Expected behavior**
The page should not reload its content that often, which might be the causation of the problem.

**Comment by Sommerli** [comment]
#488
