### ISSUE TITLE
Admins can not load givers in Overview

### ISSUE THREAD

**Issue by TTorgersen** [capgemini-stavanger/gi-en-jul#486]
After a successful login admins will not be able to fetch the data regarding givers in overview. 
However, they are able to fetch givers in "suggested givers" as this actions does not require any authentication. 
Therefore the issue is related to permissions.

**Comment by Sommerli** [comment]
Wrong configuration in Azure Portal regarding the Auth0:AzureAudience variable caused an error. 

Added /api to configuration

![image](https://user-images.githubusercontent.com/45152025/136193448-c794f0f7-bb20-4459-81af-8791f6eba860.png)


Now all authenticated calls can be completed.
