### ISSUE TITLE
Fix norwegian letters in database/mail. 

### ISSUE THREAD

**Issue by TTorgersen** [capgemini-stavanger/gi-en-jul#523]
If a family wants "pinnekjøtt" for dinner, the letter Ø will be replaced with a unreadable symbol. 

Can this be fixed with changing ".toLowerCase" to ".toLocaleLowerCase"?

**Comment by HGodal** [comment]
This problem only occurs in the automatically generated data used for local testing.
The database in the production version renders the Norwegian letters correctly.
