### ISSUE TITLE
Extract Email Templates for better maintainability

### ISSUE THREAD

**Issue by RonHaland** [capgemini-stavanger/gi-en-jul#560]
Steps:
1. Extract Email Templates to .html files.
2. EmailTemplate enum that can be used to access templates.
3. Class for generating and combining dictionaries.
4. Class for reading html files and substituting dictionary keys with values.
5. Store email titles in resx file.

This requires quite a bit of testing around emails so it should not be merged before we are ready to do so.

**Comment by TTorgersen** [comment]
Assuming this can be closed now 💯

**Comment by RonHaland** [comment]
No, this is actually not merged yet. Waiting until after the current event, as I don't want risk screwing with emails that work now during the final stretch of this years Gi en jul

**Comment by RonHaland** [comment]
Closing this as resolved 😎
