### ISSUE TITLE
Automated pipelines in Github

### ISSUE THREAD

**Issue by bra001** [capgemini-stavanger/gi-en-jul#6]
Automated pipelines in Github for build, test, and deployment.

- [ ]  Build, test and deploy **back end** when changes are merged into master
- [ ]  Build, test and deploy **front end** when changes are merged into master
- [x]  build and test when creating a pull request **back end**
- [x]  build and test when creating a pull request **front end**

**Comment by TheseusDeus** [comment]
Made new issue for the two remaining tasks, for deploying. #119
