### ISSUE TITLE
Frontend, Admin - Create suggested connections

### ISSUE THREAD

**Issue by joffe97** [capgemini-stavanger/gi-en-jul#60]
Create the suggested connections component for the admin page.
![image](https://user-images.githubusercontent.com/61537815/122942755-b9b23e00-d376-11eb-8f90-898a0ee6b678.png)

**Comment by TheseusDeus** [comment]
This and #61 should be created with material UI from the start

**Comment by TheseusDeus** [comment]
Not fully decided on how the flow of information should be
To begin with it could just display families on the left and givers on the right from the DB

**Comment by Sommerli** [comment]
#231
