### ISSUE TITLE
Add family form - improve validation (clothing sizes)

### ISSUE THREAD

**Issue by RonHaland** [capgemini-stavanger/gi-en-jul#616]
A lot of family members are missing sizes for their wishes.

Need to speak with Frog about UI & form
![image](https://user-images.githubusercontent.com/25079662/174971861-39f5b59f-c30c-4fc1-b86e-a7c959936133.png)

**Comment by hildmi** [comment]
- create popup component for categories (clothes, giftcards, footwear, toys, hobby) 
- component for wishlist
