### ISSUE TITLE
Add Automapper testing

### ISSUE THREAD

**Issue by Sommerli** [capgemini-stavanger/gi-en-jul#75]
https://docs.automapper.org/en/stable/Getting-started.html#how-do-i-test-my-mappings

Add tests to check if automapper is configured correctly.

**Comment by Sommerli** [comment]
Create a test running the following method.
`[Test]
        public void TestAutoMapperConfiguration()
        {
            AutoMapperConfiguration.Initialize().ConfigurationProvider.AssertConfigurationIsValid();
        }`

Also, configure AutoMapper correctly, making this test succeed.

**Comment by TheseusDeus** [comment]
fixed with PR #122
