### ISSUE TITLE
Frontend - Fix warnings appearing in console

### ISSUE THREAD

**Issue by joffe97** [capgemini-stavanger/gi-en-jul#82]
Multiple warnings appear in the browser console, saying that `<p>` and `<div>` tags can't be children of `<p>` tags. The issue is in `GiEnJul\ClientApp\src\routes\home\Home.tsx`, and probably other places as well. 
I think the issue can be solved by replacing the children tags with `<span>` tags.
![image](https://user-images.githubusercontent.com/61537815/123256029-c8246500-d4f0-11eb-8c14-f2595eabd283.png)

**Comment by TheseusDeus** [comment]
This is appears when running the "npm test" command
