### ISSUE TITLE
Finish institution form

### ISSUE THREAD

**Issue by MagnusVG** [capgemini-stavanger/gi-en-jul#830]
Changes:
- Checkbox renamed to "Alderstilpasset Gave"
- Tooltip behind checkbox, always shows
- Gavekort, Klær, Sko, Leker, Annet categories, in that order (?)
- Rename comment field to "Specification"
- Leker and Annet only has one field
- Proper Validation and feedback
- Feedback when submitting form

**Comment by hildmi** [comment]
missing: 
validation size: not null, form cannot be submitted is null
delete location box for giftcard?
