### ISSUE TITLE
Post prod-release updates (finished by friday)

### ISSUE THREAD

**Issue by MagnusVG** [capgemini-stavanger/gi-en-jul#976]
- [x] Fikse feilmelding på /verify /deny -> Enten mer generell eller mer spesifikk
- [x] Ny footer - HILDE
- [x] Fjerne gamle Auth0 brukere (Ble laget noen til testing?)¨
- [x] Sjekk om Super Admin brukere har Super Admin rettigheter
- [x] If age is 0, show months in RecipientDataCard - ENDRE
- [x] Knapper CMS - ENDRE
- [x] CMS kommune "Vis Informasjon"-bug Er det en bug ? 
- [x] Fikse tekst på 1,2,3 landing page ( se kommentar i issue)
- [x] Pil opp på desktop fungerer ikke, landing page( se kommentar i issue) flytter seg bare litt opp
- [x] fikse bilder sandnes kommune
- [x] går ikke an å sende inn familie institusjon
- [x] fikse bilder til kontaktkortene ( se kommentar i issue)
- [x] Kommuneinformasjon visual bugs - RONNY
- [x] setMessage() is slower than setOpen when creating users - MOE
- [x] Something wrong with the password regex when creating user - MOE
- [x] Unable to log in on newly created Admin user (localhost) - works on azureedge

**Comment by En-Lun** [comment]
![image](https://user-images.githubusercontent.com/79252702/182878489-6dd9607d-6ec5-4f26-b150-5f74b1367588.png)

**Comment by En-Lun** [comment]
![image](https://user-images.githubusercontent.com/79252702/182878830-12099b04-9d62-47d1-9c23-bf6ec7ad4c91.png)

**Comment by hildmi** [comment]
forslag til ny tekst: 

På innsamlingsdagen leverer du esken på angitt sted. Barnevernet og andre kjører så eskene ut til familiene.

**Comment by En-Lun** [comment]
![image](https://user-images.githubusercontent.com/79252702/183018198-7caaaa46-1142-4a29-9d0e-6f31b342be3f.png)
